### Loki
loki:
  enabled: false
  write:
    replicas: 1
  read:
    replicas: 1
  loki:
    auth_enabled: false
    storage:
      bucketNames:
        chunks: loki-demo-bucket
        ruler: loki-demo-bucket
        admin: loki-demo-bucket
      type: s3
      s3:
        endpoint: s3.amazonaws.com
        region: eu-central-1
        secretAccessKey: <na>
        accessKeyId: <na>
        s3ForcePathStyle: false
        insecure: false
  monitoring:   
    serviceMonitor:
      metricsInstance:
       remoteWrite:
       - url: "http://observatory-mimir-nginx/api/v1/push"
    selfMonitoring:
      logsInstance:
        clients: 
        - url: "http://observatory-mimir-nginx/api/v1/push"

### Grafana
grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki-read:3100
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: '1'
      - name: Mimir
        type: prometheus
        url: http://observatory-mimir-nginx/prometheus
      - name: Prometheus
        type: prometheus
        url: http://observatory-prometheus-server
      - name: Tempo
        type: tempo
        url: http://observatory-tempo-query-frontend:3100
  
  # dashboards:
  #   default:
  #     node-exporter:
  #       gnetId: 1860
  #       datasource: Prometheus
  # dashboardProviders: 
  #   dashboardproviders.yaml:
  #     apiVersion: 1
  #     providers:
  #     - name: 'default'
  #       orgId: 1
  #       folder: ''
  #       type: file
  #       disableDeletion: false
  #       editable: true
  #       options:
  #         path: /var/lib/grafana/dashboards/default

### Mimir
mimir-distributed:
  enabled: false
  minio:
    enabled: false
  nginx:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: mimir.endpoint
          paths:
            - path: /
              pathType: Prefix
      tls:

  mimir:
    structuredConfig:
      blocks_storage:
        backend: s3
        s3:
          bucket_name: mimir-demo-bucket-0
          access_key_id: <na>
          secret_access_key: <na>
          endpoint: s3.amazonaws.com
      alertmanager_storage:
        backend: s3
        s3:
          bucket_name: mimir-demo-bucket-0-alt
          access_key_id: <na>
          secret_access_key: <na>
          endpoint: s3.amazonaws.com
      ruler_storage:
        backend: s3
        s3:
          bucket_name: mimir-demo-bucket-0-ruler
          access_key_id: <na>
          secret_access_key: <na>
          endpoint: s3.amazonaws.com

### Promtail
promtail:
  enabled: false
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki-gateway/loki/api/v1/push

### Prometheus
prometheus:
  enabled: false
  server:
    remoteWrite:
    - url: http://observatory-mimir-nginx/api/v1/push

### Tempo

tempo-distributed:
  enabled: false
  storage:
    s3:
      endpoint: s3.amazonaws.com
      region: eu-central-1
      bucket: tempo-demo-bucket-0
      access_key: <na>
      secret_key: <na>
      insecure: false
  traces:
    otlp:
      http:
        enabled: true
        receiverConfig: {}
      grpc:
        enabled: true
        receiverConfig: {}

tempo:
  enabled: true
  tempo:
    storage:
      trace:
        s3:
          bucket: tempo-demo-bucket-0
          endpoint: s3.amazonaws.com
          region: eu-central-1
          access_key: <na>
          secret_key: <na>
          insecure: false

### Cert-Manager
cert-manager:
  enabled: false
  installCRDs: true

### OpenTelementry
opentelemetry-collector:
  enabled: true
  mode: daemonset
  config:
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: http://obs-tempo:4317
        tls:
          insecure: true
    service:
      pipelines:
        logs:
          exporters:
            - logging
            - otlp
        traces:
          exporters:
            - logging
            - otlp
          processors:
            - memory_limiter
            - batch